apiVersion: v1
kind: ReplicationController 
metadata:
  name: nginx-rc 
spec: 
  replicas: 4
  selector:
     app: nginx
  template: 
    metadata:     
       labels:
          app: nginx
    spec:
      containers:
      - name: nginx-container 
        image: muni143/myjavapp26may22:1

        ports:
        - containerPort: 8080       

