apiVersion: v1
kind: ReplicationController 
metadata:
  name: nginx-rc 
spec: 
  replicas: 4
  selector:
     app: nginx
     version: 2.6.3
  template: 
    metadata:     
       labels:
          app: nginx
          version: 2.6.3
    spec:
      containers:
      - name: ngix-container 
        image: maha4iac/myonlinebooking:3

        ports:
        - containerPort: 8080       

