apiVersion: v1
kind: ReplicationController 
metadata:
  name: nginx-rc 
spec: 
  replicas: 4
  selector:
     app: nginx
     version: 2.6.2
  template: 
    metadata:     
       labels:
          app: nginx
          version: 2.6.2
    spec:
      containers:
      - name: nginx-container 
        image: maha4iac/mymahalogin:2

        ports:
        - containerPort: 8080       

